[mgr]
prepend_keymap = [
  { on = "Z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
  { on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },

  # Chmod
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },

  # Sudo
  { on = ["R", "p", "p"], run = "plugin sudo -- paste", desc = "sudo paste" },
  { on = ["R", "P"], run = "plugin sudo -- paste --force", desc = "sudo paste (force)" },
  { on = ["R", "r"], run = "plugin sudo -- rename", desc = "sudo rename" },
  { on = ["R", "p", "l"], run = "plugin sudo -- link", desc = "sudo link" },
  { on = ["R", "p", "r"], run = "plugin sudo -- link --relative", desc = "sudo link (relative path)" },
  { on = ["R", "p", "L"], run = "plugin sudo -- hardlink", desc = "sudo hardlink" },
  { on = ["R", "a"], run = "plugin sudo -- create", desc = "sudo create" },
  { on = ["R", "d"], run = "plugin sudo -- remove", desc = "sudo trash" },
  { on = ["R", "D"], run = "plugin sudo -- remove --permanently", desc = "sudo delete" },

  # Relative motions
  { on = ["1"], run = "plugin relative-motions 1", desc = "Move in relative steps" },
  { on = ["2"], run = "plugin relative-motions 2", desc = "Move in relative steps" },
  { on = ["3"], run = "plugin relative-motions 3", desc = "Move in relative steps" },
  { on = ["4"], run = "plugin relative-motions 4", desc = "Move in relative steps" },
  { on = ["5"], run = "plugin relative-motions 5", desc = "Move in relative steps" },
  { on = ["6"], run = "plugin relative-motions 6", desc = "Move in relative steps" },
  { on = ["7"], run = "plugin relative-motions 7", desc = "Move in relative steps" },
  { on = ["8"], run = "plugin relative-motions 8", desc = "Move in relative steps" },
  { on = ["9"], run = "plugin relative-motions 9", desc = "Move in relative steps" },

  # Fchar
  { on = ["f"], run = "plugin fchar", desc = "Jump to char" },

  # Recycle-bin
  { on = ["R", "b"], run = "plugin recycle-bin", desc = "Open recycle bin menu" },

  # Restore
  { on = ["D", "u"], run = "plugin restore", desc = "Restore last deleted files/folders" },
  { on = ["D", "U"], run = "plugin restore -- --interactive", desc = "Restore deleted files/folders (Interactive)" },

  # Mount
  { on = ["M", "m"], run = "plugin mount", desc = "Mount devices" },

  # GVFS
  { on = ["M", "M"], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device then mount and jump" },
  { on = ["M", "U"], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },
  { on = ["M", "R"], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount device under cwd" },

  # Dupes
  { on = ["D", "i"], run = "plugin dupes interactive", desc = "Run dupes interactive" },
]
