[mgr]
sort_by = "natural"
linemode = "size"
show_hidden = true
scrolloff = 8

[plugin]
prepend_fetchers = [
	{ id = "git", url = "*", run = "git" },
	{ id = "git", url = "*/", run = "git" },
]

prepend_preloaders = [
  { name = "/run/user/1000/gvfs/**/*", run = "noop" },
  { name = "/run/media/rorik/**/*", run = "noop" },
]

prepend_previewers = [
  { name = "*/", run = "folder" },
  { name = "/run/user/1000/gvfs/**/*", run = "noop" },
  { name = "/run/media/rorik/**/*", run = "noop" },
]
